name: Ultra-Cloner Build Pipeline
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Engine & Clone
        run: |
          pip install requests
          python3 cloner.py MyTestClone.apk

      - name: Upload Final APK
        uses: actions/upload-artifact@v4
        with:
          name: Ultra-Cloned-Download
          path: data/output/*.apk
